name: Hello World by hogehoge

on:
  push:
    paths:
      - hogehoge
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'hogehoge'

    - name: Say Hello
      run: echo "Hello, World! by hogehoge"
