name: Hello World by frontend

on:
  push:
    paths:
      - frontend
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'frontend'

    - name: Say Hello
      run: echo "Hello, World! by frontend"
