name: Build and Release

on: push

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - run: |
          docker build -t arm64-image ./docker/
          docker run --rm -v $PWD:/workspace arm64-image

      # - name: Install ansible
      #   run: |
      #     sudo apt install ansible

      # - name: Run Ansible playbook
      #   run: ansible-playbook ansible/playbook.yml --connection=local
