name: Build and Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: QEMU のセットアップ
        uses: docker/setup-qemu-action@v2

      - name: Docker イメージのビルド
        run: docker build -t arm64-image ./docker/

      - name: Docker コンテナの実行
        run: docker run --rm -v $PWD:/workspace arm64-image bash -c "uname -a && ansible-playbook /workspace/ansible/playbook.yml --connection=local"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false

      # - name: Upload Release Artifact
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: test.txt
      #     asset_name: test.txt
      #     asset_content_type: text/plain

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: archive/test*.txt
