name: Build and Release

on:
  push:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: QEMU のセットアップ
        uses: docker/setup-qemu-action@v2

      - name: Docker イメージのビルド
        run: docker build -t arm64-image ./docker/

      - name: Docker コンテナの実行
        run: docker run --rm -v $PWD:/workspace arm64-image bash -c "uname -a && ansible-playbook /workspace/ansible/playbook.yml --connection=local"
