name: Build and Release

on: push

jobs:
  build_and_release:
    runs-on: arm64v8/ubuntu

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
            platforms: linux/arm64

      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install ansible
        run: |
          sudo apt install ansible

      - name: Run Ansible playbook
        run: ansible-playbook ansible/playbook.yml --connection=local
